kind: Service
apiVersion: v1
metadata:
  name: router-service
labels:
  app: router
spec:
  selector:
    app: router
  type: clusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  externalTrafficPolicy: Local
